name: SupplySign
main: redsgreens.SupplySign.SupplySign
version: 1.4
author: redsgreens
commands:
  supplysign:
    description: 'Used to reload data and list available SupplySign kits' 
    usage: '/supplysign <reload | listkits> (Used to reload data and list available SupplySign kits)'
